### ISSUE TITLE
cannot init/clone git submodule 'lib_vlfeat' 

### ISSUE THREAD

**Issue by whitt-s** [davidstutz/superpixels-revisited#3]
Main project requires git submodule 'lib_vlfeat', but this submodule cannot be initialized or cloned.

Possible reason is that this repository is private?
https://github.com/davidstutz/vlfeat

Note: there is no problem importing the other submodule, 'lib_seeds_revised', which is public. The problem occurs only with vlfeat.

**Comment by davidstutz** [comment]
Actually, it may be that I removed my fork of the VLFeat library but forget to update the submodule. Will fix this.
