### ISSUE TITLE
Option problem in vlfeat_slic_cli and cis_cli

### ISSUE THREAD

**Issue by Veknelyon** [davidstutz/superpixels-revisited#6]
There is a little problem in the declaration of the options in the file  https://github.com/davidstutz/superpixels-revisited/blob/master/vlfeat_slic_cli/main.cpp.
There are 2 declarations of the option _process_ (line 99 and 103).
A similar problem appears in the file https://github.com/davidstutz/superpixels-revisited/blob/master/cis_cli/main.cpp with the option _time_ (line 135 and 139).

**Comment by davidstutz** [comment]
Will look into it as soon as I have access to a setup machine.
